default: &default
  enabled: true
  abbreviation: "fws"
  short_name: "U.S. Fish & Wildlife Service"
  long_name: "U.S. Fish & Wildlife Service"
  publisher_id: grid.462979.7
  ror_ids:
    - https://ror.org/04k7dar27
  tenant_id: fws
  authentication:
    strategy: ip_address
    ranges: [ "164.159.1.1/16", "132.174.248.186" ] # large network space and also the EZProxy server
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

production: &PRODUCTION
  <<: *default
  #Add any items that need to override the defaults here
  campus_contacts: ["john_wenburg@fws.gov"]

v3_development:
  <<: *default

v3_stage:
  <<: *default

v3_production:
  <<: *PRODUCTION
