default: &default
  enabled: true
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryaddev"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_password] %>
  abbreviation: "Northwestern"
  short_name: "Northwestern University"
  long_name: "Northwestern University"
  publisher_id: grid.16753.36
  ror_ids:
    - https://ror.org/000e0be47
  tenant_id: northwestern
  identifier_service:
    provider: datacite
    prefix: "10.7959"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: true
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:northwestern.edu
    entity_domain: northwestern.edu
  default_license: cc0
  campus_contacts: ["chris-diaz@northwestern.edu"]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryadstg"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_password] %>

production:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt.cdlib.org
    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/cdl_dryad"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryad_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryad_password] %>
  identifier_service:
    provider: datacite
    prefix: "10.5061"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:datacite_password] %>
    sandbox: false
