default: &default
  enabled: true
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryaddev"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryaddev_password] %>
  abbreviation: "Riverside"
  short_name: "UC Riverside"
  long_name: "University of California, Riverside"
  publisher_id: grid.266097.c
  ror_ids:
    - https://ror.org/03nawhv43
  tenant_id: ucr
  identifier_service:
    provider: ezid
    shoulder: "doi:10.5072/FK2"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null
  authentication:
    strategy: shibboleth
    entity_id: urn:mace:incommon:ucr.edu
    entity_domain: .lib.ucr.edu
  default_license: cc0
  ## maximum total size (default 100 MB for now)
  max_submission_size: 3.0e+11
  max_total_version_size: 1.0e+10
  max_files: 1000
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here
  enabled: false

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt-stage.cdlib.org
    endpoint: "http://mrtsword-stg.cdlib.org:39001/mrtsword/collection/cdl_dryadstg"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryadstg_password] %> 

migration:
  <<: *default
  enabled: false

demo:
  <<: *default
  enabled: false

production:
  <<: *default
  #Add any items that need to override the defaults here
  repository:
    domain: https://merritt.cdlib.org
    endpoint: "http://mrtsword.cdlib.org:39001/mrtsword/collection/cdl_dryad"
    username: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryad_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:merritt_dryad_password] %>
  identifier_service:
    provider: ezid
    shoulder: "doi:10.6086/D1"
    account: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_username] %>
    password: <%= Rails.application.credentials[Rails.env.to_sym][:ezid_password] %>
    id_scheme: doi
    owner: null
  campus_contacts: ["katherine.koziar@ucr.edu"]

test:
  <<: *default
  #Add any items that need to override the defaults here
