default: &default
  enabled: true
  my_test_config_val: <%= Rails.application.credentials[Rails.env.to_sym][:another_val] %>
  abbreviation: "URI"
  short_name: "University of Rhode Island"
  long_name: "The University of Rhode Island"
  publisher_id: grid.20431.34
  ror_ids:
    - https://ror.org/013ckk937
  tenant_id: uri

  authentication:
    strategy: shibboleth
    entity_id: "https://sts.windows.net/426d2a8d-9ccd-4255-893d-0686a32c168d/"
    entity_domain: sts.windows.net
  default_license: cc0
  campus_contacts: [""]
  data_deposit_agreement: false
  partner_display: true
  covers_dpc: true

development: &DEVELOPMENT
  <<: *default
  #Add any items that need to override the defaults here

local_dev:
  <<: *DEVELOPMENT

local:
  <<: *default
  #Add any items that need to override the defaults here

stage:
  <<: *default
  #Add any items that need to override the defaults here

migration:
  <<: *default
  enabled: false

demo:
  <<: *default

production:
  <<: *default
  #Add any items that need to override the defaults here


test:
  <<: *default
  #Add any items that need to override the defaults here
