defaults: &defaults
  update_base_url: http://localhost:3000/stash/dataset
  oai_base_url: http://uc3-mrtoai-stg.cdlib.org:37001/mrtoai/oai/v2

test:
  <<: *defaults
  sets:
    - test1

localhost:
  <<: *defaults
  sets:
    - cdl_dryaddev

development:
  <<: *defaults
  update_base_url: https://dryad-dev.cdlib.org/stash/dataset
  oai_base_url: http://uc3-mrtoai-stg.cdlib.org:37001/mrtoai/oai/v2
  sets:
    - cdl_dryaddev

stage:
  <<: *defaults
  update_base_url: https://dryad-stg.cdlib.org/stash/dataset
  oai_base_url: http://uc3-mrtoai-stg.cdlib.org:37001/mrtoai/oai/v2
  sets:
    - cdl_dryadstg
    - ucsf_dryadstg
    - ucsb_dryadstg

migration:
  <<: *defaults
  update_base_url: https://dryad-migration.cdlib.org/stash/dataset
  oai_base_url: http://uc3-mrtoai-prd.cdlib.org:37001/mrtoai/oai/v2
  sets:
    - cdl_dryad

production:
  <<: *defaults
  update_base_url: https://dryadx2-prd.cdlib.org/stash/stash/dataset
  oai_base_url: http://uc3-mrtoai-prd.cdlib.org:37001/mrtoai/oai/v2
  sets:
    - cdl_dryad
    - lbnl_dash
    - uci_dash
    - ucb_dash
    - ucd_lib_dash
    - ucla_dash
    - ucm_dash
    - ucop_dash
    - ucr_lib_dash
    - ucsb_dash
    - ucsc_dash
    - ucsf_lib_datashare
