---
:concurrency: 5
stage:
  :concurrency: 10
production:
  :concurrency: 15
:queues:
  - submission
  - submission_check
  - submission_file
  - publication
  - archive_analyzer
  - zenodo_software
  - zenodo_supp
  - zenodo_copy
  - big_submission_file
  - deletion
  - critical
  - default
  - low
:limits:
  big_submission_file: 7
  archive_analyzer: 5
