---
:concurrency: 5
stage:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - submission
  - submission_check
  - submission_file
  - zenodo_software
  - zenodo_supp
  - zenodo_copy
  - big_submission_file
  - critical
  - default
  - low
:limits:
  big_submission_file: 7
